from django.contrib import admin
from ifoodsocial.models import Cidade, Bairro, Localidade, Empreendimento, Funcionario, Cliente, FormaPagto, Pedido, Categoria, Produto, ItemPedido, AvaliacaoPedido, Disponibilidade, DisponExcecao, Entrega, Evento, RastreamentoPedido, Cardapio, EmprendFuncionario, SecaoCardapio, SecaoProduto


admin.site.register(Cidade)
admin.site.register(Bairro)
admin.site.register(Localidade)
admin.site.register(Empreendimento)
admin.site.register(Funcionario)
admin.site.register(Cliente)
admin.site.register(FormaPagto)
admin.site.register(Pedido)
admin.site.register(Categoria)
admin.site.register(Produto)
admin.site.register(ItemPedido)
admin.site.register(AvaliacaoPedido)
admin.site.register(Disponibilidade)
admin.site.register(DisponExcecao)
admin.site.register(Entrega)
admin.site.register(Evento)
admin.site.register(RastreamentoPedido)
admin.site.register(Cardapio)
admin.site.register(EmprendFuncionario)
admin.site.register(SecaoCardapio)
admin.site.register(SecaoProduto)
